### ISSUE TITLE
OG / Twitter metadata

### ISSUE THREAD

**Issue by nothingismagick** [iotaledger/spark-wallet#81]
I created a request, and pasted that request  link in discord. I think a more appropriate text and image would be good. 
![_20191219_165021](https://user-images.githubusercontent.com/35242872/71187509-81acd500-227f-11ea-8d2a-792004e16c76.JPG)

**Comment by cvarley100** [comment]
@nothingismagick By 'more appropriate image' and text, what do you mean in particular?
