### ISSUE TITLE
Mirrored image in QR-Scan process 

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/spark-wallet#82]
The image is horizontally mirrored when opening spark on iPad 6 (iPadOS 13.3) and iPhone 6 (iOS 12.4.3) via Safari Browser.

![BFA37FC1-41F9-4A14-86D8-AACBE57C7A6A](https://user-images.githubusercontent.com/17240275/71190269-8d4eca80-2284-11ea-8f84-684f41e924aa.jpeg)

**Comment by nothingismagick** [comment]
Same in android
